# Generated by Django 5.2.6 on 2025-09-25 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        help_text="Upload your resume (PDF or DOCX).",
                        null=True,
                        upload_to="resumes/",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                (
                    "about_me_input",
                    models.TextField(
                        blank=True, help_text="Raw notes about yourself for the AI."
                    ),
                ),
                (
                    "about_me_generated",
                    models.TextField(
                        blank=True,
                        help_text="Polished 'About Me' section generated by AI.",
                    ),
                ),
                (
                    "skills_input",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of your skills."
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to="backgrounds/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("technologies", models.CharField(blank=True, max_length=200)),
                ("description_input", models.TextField(blank=True)),
                ("description_generated", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="persona.portfolio",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
    ]
