# Generated by Django 5.2.6 on 2025-09-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
    ]
