# Generated by Django 5.2.6 on 2025-09-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0002_portfolio_email_portfolio_linkedin_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="description_input",
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[("experience", "Work Experience"), ("project", "Project")],
                default="project",
                max_length=20,
            ),
        ),
    ]
