# Generated by Django 5.2.6 on 2025-09-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0003_remove_project_description_input_project_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="github_url",
            field=models.URLField(blank=True),
        ),
    ]
