# Generated by Django 5.2.6 on 2025-09-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0004_portfolio_github_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="design_template",
            field=models.CharField(
                choices=[("modern", "Modern Dark"), ("minimalist", "Clean Minimalist")],
                default="modern",
                max_length=20,
            ),
        ),
    ]
