# Generated by Django 5.2.6 on 2025-09-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0005_portfolio_design_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="design_template",
            field=models.CharField(
                choices=[
                    ("modern", "Modern Dark"),
                    ("minimalist", "Clean Minimalist"),
                    ("creative", "Creative Colorful"),
                    ("professional", "Professional Light"),
                    ("experimental", "Experimental"),
                ],
                default="modern",
                max_length=20,
            ),
        ),
    ]
